---
# tasks file for install-yarn

- name: Install nodejs 12
  snap:
    name: node
    classic: yes
    channel: 12

- name: Add Apt signing key, for Yarn repo
  apt_key:
    url: '{{ yarn_public_key }}'
    state: present

- name: Add Yarn repository
  apt_repository:
    repo: '{{ yarn_repo }}'
    state: present

- name: Yarn install
  apt:
    name: yarn
    state: present
    update_cache: yes