#!/bin/sh
# chkconfig: 2345 90 30
# description:  anycable-go startup script
# processname: anycable-go

KIND="anycable-go"
start() {
    echo -n $"Starting $KIND services: "
#    cd /var/app/current && /bin/bash -lc 'bundle exec anycable' &
    /usr/bin/anycable-go --host=0.0.0.0 &
    echo
    }	

stop() {
    echo -n $"Shutting down $KIND services: "
    pkill anycable-go
    echo
    }	

restart() {
    echo -n $"Restarting $KIND services: "	
    pkill anycable-go
    /usr/bin/anycable-go --host=0.0.0.0 &
    echo
    }	

case "$1" in
    start)
	start
    ;;
    stop)
	stop
    ;;
    restart)
	restart
    ;;
    status)
	status -p anycable
    ;;
     *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 2
esac
exit $?